use quote::{format_ident, quote};
use syn::{Data, DeriveInput, Fields, parse_macro_input};

pub fn derive_object(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    let object_name = &input.ident;
    let visibility = &input.vis;
    let builder_name = format_ident!("{}Builder", object_name);
    let handler_name = format_ident!("{}Handler", object_name);

    let fields = match &input.data {
        Data::Struct(data) => match &data.fields {
            Fields::Named(named) => &named.named,
            _ => panic!("Object only supports structs with named fields."),
        },
        _ => panic!("Object can only be derived for structs."),
    };

    let mut field_accessors = Vec::with_capacity(fields.len());
    let mut component_accessors = Vec::with_capacity(fields.len());
    let mut trackable_infos = Vec::with_capacity(fields.len());

    for field in fields {
        let field_ident = field.ident.as_ref().unwrap();
        let field_ty = &field.ty;
        let is_trackable = field
            .attrs
            .iter()
            .any(|attr| attr.path().is_ident("trackable"));

        if !is_trackable {
            continue;
        }

        let field_visibility = &field.vis;
        field_accessors.push(quote! {
            #field_visibility fn #field_ident(
                &self,
            ) -> <#field_ty as crate::core::Trackable>::Handle {
                // Forward to the component-specific handle generated by `Trackable`.
                <#field_ty as crate::core::Trackable>::handle(
                    std::rc::Rc::clone(&self.world),
                    self.entity,
                )
            }
        });

        trackable_infos.push(quote! {
            <#field_ty>::INFO
        });

        component_accessors.push(quote! {
            impl crate::core::objects::ObjectBuilderComponent<#field_ty> for #builder_name {
                fn component_mut(&mut self) -> &mut #field_ty {
                    &mut self.object.#field_ident
                }
            }
        });
    }

    let count = trackable_infos.len();
    let infos_ident = format_ident!("__{}_TRACKABLES", object_name.to_string().to_uppercase());
    let infos_fn_ident = format_ident!("__{}_trackables", object_name.to_string().to_lowercase());

    let expanded = quote! {
        /// Builder generated for this scene object.
        #visibility struct #builder_name {
            object: #object_name,
        }

        impl #builder_name {
            /// Creates a builder initialized with the object's defaults.
            pub fn new() -> Self {
                Self {
                    object: <#object_name as Default>::default(),
                }
            }

            /// Finishes configuring the scene object.
            pub fn build(self) -> #object_name {
                self.object
            }
        }

        impl Default for #builder_name {
            fn default() -> Self {
                Self::new()
            }
        }

        #(#component_accessors)*

        /// Typed handler for an entity spawned into a scene.
        #visibility struct #handler_name {
            world: crate::core::SceneWorld,
            entity: hecs::Entity,
        }

        #[allow(non_upper_case_globals)]
        const #infos_ident: [crate::core::TrackableInfo; #count] = [
            #(#trackable_infos),*
        ];

        fn #infos_fn_ident() -> &'static [crate::core::TrackableInfo] {
            &#infos_ident
        }

        impl #object_name {
            /// Builds a typed handler from a spawned entity id.
            pub fn handler(world: crate::core::SceneWorld, entity: hecs::Entity) -> #handler_name {
                #handler_name { world, entity }
            }
        }

        impl #handler_name {
            #(#field_accessors)*
        }

        impl crate::core::objects::Object for #object_name {
            type Handler = #handler_name;

            fn handler(world: crate::core::SceneWorld, entity: hecs::Entity) -> Self::Handler {
                #handler_name { world, entity }
            }

            fn inspection() -> crate::core::components::Inspection {
                crate::core::components::Inspection {
                    get: |_world, _entity| #infos_fn_ident(),
                }
            }
        }
    };

    proc_macro::TokenStream::from(expanded)
}
