use quote::{format_ident, quote};
use syn::{Data, DeriveInput, Fields, parse_macro_input};

// Converts `ObjectBundle` into `Object` so the generated handle reads naturally.
fn bundle_handle_name(struct_name: &syn::Ident) -> proc_macro2::Ident {
    let name = struct_name.to_string();
    let handle_name = name.strip_suffix("Bundle").unwrap_or(&name).to_string();
    format_ident!("{}", handle_name)
}

pub fn derive_object(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    let bundle_name = &input.ident;
    let handle_name = bundle_handle_name(bundle_name);

    let fields = match &input.data {
        Data::Struct(data) => match &data.fields {
            Fields::Named(named) => &named.named,
            _ => panic!("Object only supports structs with named fields."),
        },
        _ => panic!("Object can only be derived for structs."),
    };

    let mut field_accessors = Vec::with_capacity(fields.len());
    let mut trackable_infos = Vec::with_capacity(fields.len());

    for field in fields {
        let field_ident = field.ident.as_ref().unwrap();
        let field_ty = &field.ty;
        let is_trackable = field
            .attrs
            .iter()
            .any(|attr| attr.path().is_ident("trackable"));

        if !is_trackable {
            continue;
        }

        field_accessors.push(quote! {
            pub fn #field_ident<'a>(
                &self,
                scene: &'a mut crate::core::Scene,
            ) -> <#field_ty as crate::core::Trackable>::Handle<'a> {
                // Forward to the component-specific handle generated by `Trackable`.
                <#field_ty as crate::core::Trackable>::handle(scene, self.entity)
            }
        });

        trackable_infos.push(quote! {
            <#field_ty>::INFO
        });
    }

    let count = trackable_infos.len();
    let infos_ident = format_ident!("__{}_TRACKABLES", bundle_name.to_string().to_uppercase());
    let infos_fn_ident = format_ident!("__{}_trackables", bundle_name.to_string().to_lowercase());

    let expanded = quote! {
        /// Typed entity handle generated from the bundle name.
        pub struct #handle_name {
            entity: hecs::Entity,
        }

        #[allow(non_upper_case_globals)]
        const #infos_ident: [crate::core::TrackableInfo; #count] = [
            #(#trackable_infos),*
        ];

        fn #infos_fn_ident() -> &'static [crate::core::TrackableInfo] {
            &#infos_ident
        }

        impl #bundle_name {
            /// Builds a handle wrapper from a spawned entity id.
            pub fn handle(entity: hecs::Entity) -> #handle_name {
                #handle_name { entity }
            }
        }

        impl #handle_name {
            #(#field_accessors)*
        }

        impl crate::core::objects::Object for #bundle_name {
            type Handle = #handle_name;

            fn handle(entity: hecs::Entity) -> Self::Handle {
                #handle_name { entity }
            }

            fn inspection() -> crate::core::components::Inspection {
                crate::core::components::Inspection {
                    get: |_world, _entity| #infos_fn_ident(),
                }
            }
        }
    };

    proc_macro::TokenStream::from(expanded)
}
