use crate::core::{
    components::{Simulation, SimulationState},
    objects::{Object, ObjectHandler},
};

/// Associates a simulation state type with a regular scene object.
///
/// This is generated by `#[derive(Object)]` when `simulation = State` is set.
pub trait SimulationObject: Object {
    type State: SimulationState;
}

/// Schedules one explicit simulation update at the handler's current timeline time.
#[doc(hidden)]
pub fn schedule_simulation_update(handler: &impl ObjectHandler) {
    let animator = handler.object_animator();
    animator.assert_finite_scope();
    handler
        .object_world()
        .borrow()
        .get::<&mut Simulation>(handler.entity())
        .expect("Simulated object must contain a Simulation component.")
        .schedule_update(animator.time());
}

/// Reads the simulation state currently evaluated by the scene.
#[doc(hidden)]
pub fn read_simulation_state<H, R>(
    handler: &H,
    read: impl FnOnce(&<H::Object as SimulationObject>::State) -> R,
) -> R
where
    H: ObjectHandler,
    H::Object: SimulationObject,
{
    let world = handler.object_world();
    let world = world.borrow();
    world
        .get::<&Simulation>(handler.entity())
        .expect("Simulated object must contain a Simulation component.")
        .read_state(read)
}

/// Schedules a deterministic simulation-state write at the current timeline time.
#[doc(hidden)]
pub fn schedule_simulation_write<H>(
    handler: &H,
    mutation: impl Fn(&mut <H::Object as SimulationObject>::State) + Send + Sync + 'static,
) where
    H: ObjectHandler,
    H::Object: SimulationObject,
{
    let animator = handler.object_animator();
    animator.assert_finite_scope();
    handler
        .object_world()
        .borrow()
        .get::<&mut Simulation>(handler.entity())
        .expect("Simulated object must contain a Simulation component.")
        .schedule_mutation(animator.time(), mutation);
}
