use crate::core::{Scene, Task, Tween, components::Animation};

pub struct Animator {
    tasks: Vec<Task>,
}
impl Animator {
    /// Creates an empty sequential animation timeline.
    pub fn new() -> Self {
        Self { tasks: vec![] }
    }

    /// Adds a task to the end of the animation timeline.
    pub fn play(&mut self, task: Task) {
        self.tasks.push(task);
    }

    /// Plays the task generated by the given tween.
    ///
    /// Note that this is equivalent to `a.play(tween.task())`.
    pub fn tween(&mut self, tween: Tween) {
        self.play(tween.task());
    }

    /// Adds a wait task that pauses the timeline for the specified duration.
    ///
    /// Note that this is equivalent to `a.play(Task::Wait(duration))`.
    pub fn wait(&mut self, duration: f32) {
        self.play(Task::Wait(duration));
    }

    /// Adds a group of tasks that start simultaneously and waits for the longest one to finish.
    ///
    /// Note that this is equivalent to `a.play(Task::All(tasks))`.
    pub fn all(&mut self, tasks: Vec<Task>) {
        self.play(Task::All(tasks));
    }

    /// Compiles scheduled tasks into scene tracks and returns the total duration.
    ///
    /// Tasks added with [`Self::play`] run sequentially. Nested [`Task::All`]
    /// tasks share the same start time and advance the timeline by their longest
    /// child.
    pub fn get_duration(&self, scene: &mut Scene) -> f32 {
        let mut time = 0.0;

        for task in &self.tasks {
            time += Self::process_task(scene, task, time);
        }

        time
    }

    /// Adds a task's keyframes at `start_time` and returns its elapsed duration.
    fn process_task(scene: &mut Scene, task: &Task, start_time: f32) -> f32 {
        match task {
            Task::Tween {
                entity,
                type_id,
                track_id,
                track_setter,
                from,
                to,
                duration,
                easing,
            } => {
                scene
                    .get_world()
                    .get::<&mut Animation>(*entity)
                    .unwrap()
                    .animate(
                        start_time,
                        *type_id,
                        *track_id,
                        *track_setter,
                        *from,
                        *to,
                        *duration,
                        *easing,
                    );

                *duration
            }

            Task::Wait(duration) => *duration,

            Task::All(tasks) => {
                let mut max_duration: f32 = 0.0;

                for task in tasks {
                    let duration = Self::process_task(scene, task, start_time);

                    max_duration = max_duration.max(duration);
                }

                max_duration
            }
        }
    }
}
