use crate::core::{Scene, Task, Tween, components::Animation};

pub struct Animator {
    tasks: Vec<Task>,
}
impl Animator {
    /// Creates an empty sequential animation timeline.
    pub fn new() -> Self {
        Self { tasks: vec![] }
    }

    /// Adds a task to the end of the animation timeline.
    pub fn play(&mut self, task: Task) {
        self.tasks.push(task);
    }

    /// Plays the task generated by the given tween.
    ///
    /// Note that this is equivalent to `a.play(tween.task())`.
    pub fn tween(&mut self, tween: Tween) {
        self.play(tween.task());
    }

    /// Adds a wait task that pauses the timeline for the specified duration.
    ///
    /// Note that this is equivalent to `a.play(Task::Wait(duration))`.
    pub fn wait(&mut self, duration: f32) {
        self.play(Task::Wait(duration));
    }

    /// Adds the tasks scheduled by `schedule` as a simultaneous group.
    ///
    /// The timeline waits for the longest task in the group to finish.
    pub fn all(&mut self, schedule: impl FnOnce(&mut Animator)) {
        let mut group = Animator::new();

        schedule(&mut group);

        self.play(Task::All(group.tasks));
    }

    /// Repeats the sequence of tasks scheduled by `schedule`.
    pub fn repeat(&mut self, repetitions: usize, schedule: impl FnOnce(&mut Animator)) {
        let mut group = Animator::new();

        schedule(&mut group);

        self.play(Task::Repeat(repetitions, group.tasks));
    }

    /// Compiles scheduled tasks into scene tracks and returns the total duration.
    ///
    /// Tasks added with [`Self::play`] run sequentially. Nested [`Task::All`]
    /// tasks share the same start time and advance the timeline by their longest
    /// child. [`Task::Repeat`] tasks advance it once for each repetition.
    pub fn get_duration(&self, scene: &mut Scene) -> f32 {
        let mut time = 0.0;

        for task in &self.tasks {
            time += Self::process_task(scene, task, time);
        }

        time
    }

    /// Adds a task's keyframes at `start_time` and returns its elapsed duration.
    fn process_task(scene: &mut Scene, task: &Task, start_time: f32) -> f32 {
        match task {
            Task::Tween {
                entity,
                type_id,
                track_info,
                from,
                to,
                duration,
                easing,
            } => {
                scene
                    .get_world()
                    .get::<&mut Animation>(*entity)
                    .unwrap()
                    .animate(
                        start_time, *type_id, track_info, *from, *to, *duration, *easing,
                    );

                *duration
            }

            Task::Wait(duration) => *duration,

            Task::All(tasks) => {
                let mut max_duration: f32 = 0.0;

                for task in tasks {
                    let duration = Self::process_task(scene, task, start_time);

                    max_duration = max_duration.max(duration);
                }

                max_duration
            }

            Task::Repeat(repetitions, tasks) => {
                let mut duration = 0.0;

                for _ in 0..*repetitions {
                    for task in tasks {
                        duration += Self::process_task(scene, task, start_time + duration);
                    }
                }

                duration
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn all_collects_tasks_scheduled_by_a_closure() {
        let mut animator = Animator::new();

        schedule_group(&mut animator);

        assert_eq!(animator.tasks.len(), 1);

        let Task::All(tasks) = &animator.tasks[0] else {
            panic!("The scheduled task must be an all group.");
        };

        assert_eq!(tasks.len(), 2);
        assert!(matches!(tasks[0], Task::Wait(1.0)));
        assert!(matches!(tasks[1], Task::Wait(2.0)));
    }

    fn schedule_group(animator: &mut Animator) {
        animator.all(|animator| {
            animator.wait(1.0);
            animator.wait(2.0);
        });
    }

    #[test]
    fn repeat_collects_tasks_scheduled_by_a_closure() {
        let mut animator = Animator::new();

        animator.repeat(3, |animator| {
            animator.wait(1.0);
            animator.wait(2.0);
        });

        assert_eq!(animator.tasks.len(), 1);

        let Task::Repeat(repetitions, tasks) = &animator.tasks[0] else {
            panic!("The scheduled task must be a repeat.");
        };

        assert_eq!(*repetitions, 3);
        assert_eq!(tasks.len(), 2);
        assert!(matches!(tasks[0], Task::Wait(1.0)));
        assert!(matches!(tasks[1], Task::Wait(2.0)));
    }

    #[test]
    fn repeat_runs_its_tasks_sequentially() {
        let mut animator = Animator::new();
        let mut scene = Scene::new();

        animator.repeat(3, |animator| {
            animator.wait(1.0);
            animator.wait(2.0);
        });
        animator.wait(1.0);

        assert_eq!(animator.get_duration(&mut scene), 10.0);
    }

    #[test]
    fn repeat_continues_tweens_from_the_previous_repetition() {
        let mut animator = Animator::new();
        let mut scene = Scene::new();
        let circle = scene.create(crate::core::objects::CircleBundle::default());

        animator.repeat(2, |animator| {
            animator.tween(circle.transform(&mut scene).position.x(100.0).duration(1.0));
            animator.tween(
                circle
                    .transform(&mut scene)
                    .position
                    .x(-100.0)
                    .duration(1.0),
            );
        });

        assert_eq!(animator.get_duration(&mut scene), 4.0);

        scene.update(2.0);
        assert_eq!(position_x(&scene), -100.0);

        scene.update(3.0);
        assert_eq!(position_x(&scene), 100.0);

        scene.update(4.0);
        assert_eq!(position_x(&scene), -100.0);
    }

    fn position_x(scene: &Scene) -> f32 {
        let mut query = scene
            .get_world()
            .query::<&crate::core::components::Transform>();

        query.iter().next().unwrap().position.x
    }
}
