use crate::core::{Scene, Task, Tween, components::Animation};

pub struct Animator {
    tasks: Vec<Task>,
    start_time: f32,
    elapsed: f32,
    scheduling: Scheduling,
    scene_time: std::rc::Rc<std::cell::Cell<f32>>,
}

#[derive(Clone, Copy)]
enum Scheduling {
    Sequential,
    Parallel,
}

impl Animator {
    /// Creates an empty sequential animation timeline.
    pub fn new() -> Self {
        Self::with_scene_time(std::rc::Rc::new(std::cell::Cell::new(0.0)))
    }

    pub(crate) fn with_scene_time(scene_time: std::rc::Rc<std::cell::Cell<f32>>) -> Self {
        scene_time.set(0.0);

        Self {
            tasks: vec![],
            start_time: 0.0,
            elapsed: 0.0,
            scheduling: Scheduling::Sequential,
            scene_time,
        }
    }

    fn group(&self, scheduling: Scheduling) -> Self {
        let start_time = match self.scheduling {
            Scheduling::Sequential => self.get_time(),
            Scheduling::Parallel => self.start_time,
        };

        Self {
            tasks: vec![],
            start_time,
            elapsed: 0.0,
            scheduling,
            scene_time: std::rc::Rc::clone(&self.scene_time),
        }
    }

    /// Adds a task to the end of the animation timeline.
    pub fn play(&mut self, task: Task) {
        let duration = Self::task_duration(&task);
        self.tasks.push(task);

        match self.scheduling {
            Scheduling::Sequential => self.elapsed += duration,
            Scheduling::Parallel => self.elapsed = self.elapsed.max(duration),
        }

        self.sync_scene_time();
    }

    /// Plays the task generated by the given tween.
    ///
    /// Note that this is equivalent to `a.play(tween.task())`.
    pub fn tween(&mut self, tween: Tween) {
        self.play(tween.task());
    }

    /// Adds a wait task that pauses the timeline for the specified duration.
    ///
    /// Note that this is equivalent to `a.play(Task::Wait(duration))`.
    pub fn wait(&mut self, duration: f32) {
        self.play(Task::Wait(duration));
    }

    /// Adds the tasks scheduled by `schedule` as a sequential group.
    pub fn chain(&mut self, schedule: impl FnOnce(&mut Animator)) {
        let mut group = self.group(Scheduling::Sequential);

        schedule(&mut group);

        self.play(Task::Chain(group.tasks));
    }

    /// Adds the tasks scheduled by `schedule` as a simultaneous group.
    ///
    /// The timeline waits for the longest task in the group to finish.
    pub fn all(&mut self, schedule: impl FnOnce(&mut Animator)) {
        let mut group = self.group(Scheduling::Parallel);

        schedule(&mut group);

        self.play(Task::All(group.tasks));
    }

    /// Repeats the sequence of tasks scheduled by `schedule`.
    pub fn repeat(&mut self, repetitions: usize, schedule: impl FnOnce(&mut Animator)) {
        let mut group = self.group(Scheduling::Sequential);

        schedule(&mut group);

        self.play(Task::Repeat(repetitions, group.tasks));
    }

    /// Returns the current timeline position used to schedule the next task.
    pub fn get_time(&self) -> f32 {
        self.start_time + self.elapsed
    }

    /// Compiles scheduled tasks into scene tracks and returns the total duration.
    ///
    /// Tasks added with [`Self::play`] run sequentially. [`Task::Chain`] tasks
    /// advance after each child. Nested [`Task::All`] tasks share the same start
    /// time and advance the timeline by their longest child. [`Task::Repeat`]
    /// tasks advance once for each repetition.
    pub fn get_duration(&self, scene: &mut Scene) -> f32 {
        let mut time = 0.0;

        for task in &self.tasks {
            time += Self::process_task(scene, task, time);
        }

        time
    }

    /// Adds a task's keyframes at `start_time` and returns its elapsed duration.
    fn process_task(scene: &mut Scene, task: &Task, start_time: f32) -> f32 {
        match task {
            Task::Tween {
                entity,
                type_id,
                track_info,
                from,
                to,
                duration,
                easing,
            } => {
                scene
                    .get_world()
                    .get::<&mut Animation>(*entity)
                    .unwrap()
                    .animate(
                        start_time,
                        *type_id,
                        track_info,
                        from.clone(),
                        to.clone(),
                        *duration,
                        *easing,
                    );

                *duration
            }

            Task::Wait(duration) => *duration,

            Task::Chain(tasks) => {
                let mut duration = 0.0;

                for task in tasks {
                    duration += Self::process_task(scene, task, start_time + duration);
                }

                duration
            }

            Task::All(tasks) => {
                let mut max_duration: f32 = 0.0;

                for task in tasks {
                    let duration = Self::process_task(scene, task, start_time);

                    max_duration = max_duration.max(duration);
                }

                max_duration
            }

            Task::Repeat(repetitions, tasks) => {
                let mut duration = 0.0;

                for _ in 0..*repetitions {
                    for task in tasks {
                        duration += Self::process_task(scene, task, start_time + duration);
                    }
                }

                duration
            }
        }
    }

    fn sync_scene_time(&self) {
        self.scene_time.set(self.get_time());
    }

    fn task_duration(task: &Task) -> f32 {
        match task {
            Task::Tween { duration, .. } | Task::Wait(duration) => *duration,
            Task::Chain(tasks) => tasks.iter().map(Self::task_duration).sum(),
            Task::All(tasks) => tasks.iter().map(Self::task_duration).fold(0.0, f32::max),
            Task::Repeat(repetitions, tasks) => {
                *repetitions as f32 * tasks.iter().map(Self::task_duration).sum::<f32>()
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use crate::core::{components::Transform, objects::CircleBuilder};

    use super::*;

    #[test]
    fn chain_collects_tasks_scheduled_by_a_closure() {
        let mut animator = Animator::new();

        animator.chain(|animator| {
            animator.wait(1.0);
            animator.wait(2.0);
        });

        assert_eq!(animator.tasks.len(), 1);

        let Task::Chain(tasks) = &animator.tasks[0] else {
            panic!("The scheduled task must be a chain group.");
        };

        assert_eq!(tasks.len(), 2);
        assert!(matches!(tasks[0], Task::Wait(1.0)));
        assert!(matches!(tasks[1], Task::Wait(2.0)));
    }

    #[test]
    fn current_time_follows_sequential_and_parallel_groups() {
        let mut animator = Animator::new();

        animator.wait(1.0);
        assert_eq!(animator.get_time(), 1.0);

        animator.all(|animator| {
            animator.wait(2.0);
            assert_eq!(animator.get_time(), 3.0);

            animator.chain(|animator| {
                animator.wait(3.0);
                assert_eq!(animator.get_time(), 4.0);
            });

            assert_eq!(animator.get_time(), 4.0);
        });

        assert_eq!(animator.get_time(), 4.0);
    }

    #[test]
    fn chain_runs_its_tasks_sequentially_inside_all() {
        let mut animator = Animator::new();
        let mut scene = Scene::new();

        animator.all(|animator| {
            animator.chain(|animator| {
                animator.wait(1.0);
                animator.wait(2.0);
            });
            animator.wait(2.0);
        });

        assert_eq!(animator.get_duration(&mut scene), 3.0);
    }

    #[test]
    fn all_collects_tasks_scheduled_by_a_closure() {
        let mut animator = Animator::new();

        schedule_group(&mut animator);

        assert_eq!(animator.tasks.len(), 1);

        let Task::All(tasks) = &animator.tasks[0] else {
            panic!("The scheduled task must be an all group.");
        };

        assert_eq!(tasks.len(), 2);
        assert!(matches!(tasks[0], Task::Wait(1.0)));
        assert!(matches!(tasks[1], Task::Wait(2.0)));
    }

    fn schedule_group(animator: &mut Animator) {
        animator.all(|animator| {
            animator.wait(1.0);
            animator.wait(2.0);
        });
    }

    #[test]
    fn repeat_collects_tasks_scheduled_by_a_closure() {
        let mut animator = Animator::new();

        animator.repeat(3, |animator| {
            animator.wait(1.0);
            animator.wait(2.0);
        });

        assert_eq!(animator.tasks.len(), 1);

        let Task::Repeat(repetitions, tasks) = &animator.tasks[0] else {
            panic!("The scheduled task must be a repeat.");
        };

        assert_eq!(*repetitions, 3);
        assert_eq!(tasks.len(), 2);
        assert!(matches!(tasks[0], Task::Wait(1.0)));
        assert!(matches!(tasks[1], Task::Wait(2.0)));
    }

    #[test]
    fn repeat_runs_its_tasks_sequentially() {
        let mut animator = Animator::new();
        let mut scene = Scene::new();

        animator.repeat(3, |animator| {
            animator.wait(1.0);
            animator.wait(2.0);
        });
        animator.wait(1.0);

        assert_eq!(animator.get_duration(&mut scene), 10.0);
    }

    #[test]
    fn repeat_continues_tweens_from_the_previous_repetition() {
        let mut animator = Animator::new();
        let mut scene = Scene::new();
        let circle = scene.create(CircleBuilder::new().build());

        animator.repeat(2, |animator| {
            animator.tween(circle.position.x(100.0).duration(1.0));
            animator.tween(circle.position.x(-100.0).duration(1.0));
        });

        assert_eq!(animator.get_duration(&mut scene), 4.0);

        scene.update(2.0);
        assert_eq!(position_x(&scene), -100.0);

        scene.update(3.0);
        assert_eq!(position_x(&scene), 100.0);

        scene.update(4.0);
        assert_eq!(position_x(&scene), -100.0);
    }

    fn position_x(scene: &Scene) -> f32 {
        let world = scene.get_world();
        let mut query = world.query::<&Transform>();

        query.iter().next().unwrap().position.x
    }
}
