use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::core::Scene;

const PROJECT_PATH: &str = ".kinematic/project.ron";

/// Factory generated by [`crate::scene`] for a project scene.
pub type SceneFactory = fn((u32, u32)) -> Scene;

#[derive(Clone, Copy, Debug, Deserialize, PartialEq, Serialize)]
#[serde(default)]
pub(crate) struct ProjectSettings {
    pub(crate) resolution: (u32, u32),
    pub(crate) fps: u32,
}

impl Default for ProjectSettings {
    fn default() -> Self {
        Self {
            resolution: (1280, 720),
            fps: 60,
        }
    }
}

impl ProjectSettings {
    fn load() -> Self {
        let path = Path::new(PROJECT_PATH);

        match std::fs::read_to_string(path) {
            Ok(contents) => match ron::from_str(&contents) {
                Ok(settings) if Self::is_valid(&settings) => settings,
                Ok(_) => {
                    eprintln!(
                        "Could not use {PROJECT_PATH}: values must be positive and resolution dimensions must be even."
                    );
                    let settings = Self::default();
                    settings.save();
                    settings
                }
                Err(error) => {
                    eprintln!("Could not parse {PROJECT_PATH}: {error}.");
                    let settings = Self::default();
                    settings.save();
                    settings
                }
            },
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
                let settings = Self::default();
                settings.save();
                settings
            }
            Err(error) => {
                eprintln!("Could not read {PROJECT_PATH}: {error}.");
                Self::default()
            }
        }
    }

    pub(crate) fn save(&self) {
        if let Err(error) = write(self, Path::new(PROJECT_PATH)) {
            eprintln!("Could not write {PROJECT_PATH}: {error}.");
        }
    }

    fn is_valid(settings: &Self) -> bool {
        settings.resolution.0 > 0
            && settings.resolution.1 > 0
            && settings.resolution.0.is_multiple_of(2)
            && settings.resolution.1.is_multiple_of(2)
            && settings.fps > 0
            && settings.resolution.0 <= i32::MAX as u32
            && settings.resolution.1 <= i32::MAX as u32
            && settings.fps <= i32::MAX as u32
    }
}

pub(crate) struct Project {
    pub(crate) name: &'static str,
    pub(crate) settings: ProjectSettings,
    pub(crate) scenes: Vec<SceneFactory>,
}

impl Project {
    pub(crate) fn new(name: &'static str, scenes: Vec<SceneFactory>) -> Self {
        Self {
            name,
            settings: ProjectSettings::load(),
            scenes,
        }
    }

    pub(crate) fn validate(&self) {
        assert!(
            !self.scenes.is_empty(),
            "Project must contain at least one scene."
        );
        assert!(ProjectSettings::is_valid(&self.settings));
    }
}

fn write(settings: &ProjectSettings, path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    if let Some(directory) = path.parent() {
        std::fs::create_dir_all(directory)?;
    }

    let contents = ron::ser::to_string_pretty(settings, ron::ser::PrettyConfig::default())?;
    std::fs::write(path, format!("{contents}\n"))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn project_settings_have_editor_defaults() {
        assert_eq!(
            ProjectSettings::default(),
            ProjectSettings {
                resolution: (1280, 720),
                fps: 60,
            }
        );
    }

    #[test]
    fn project_settings_require_exportable_values() {
        assert!(ProjectSettings::is_valid(&ProjectSettings::default()));
        assert!(!ProjectSettings::is_valid(&ProjectSettings {
            resolution: (1279, 720),
            fps: 60,
        }));
        assert!(!ProjectSettings::is_valid(&ProjectSettings {
            resolution: (1280, 720),
            fps: 0,
        }));
    }

    #[test]
    fn project_settings_are_written_as_readable_ron() {
        let directory = std::env::temp_dir().join(format!(
            "kinematic-project-settings-test-{}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        let path = directory.join("project.ron");
        let settings = ProjectSettings {
            resolution: (1920, 1080),
            fps: 30,
        };

        write(&settings, &path).unwrap();

        let contents = std::fs::read_to_string(&path).unwrap();
        let loaded: ProjectSettings = ron::from_str(&contents).unwrap();
        assert_eq!(loaded, settings);
        assert!(contents.contains("resolution: (1920, 1080)"));
        assert!(contents.contains("fps: 30"));

        std::fs::remove_dir_all(directory).unwrap();
    }
}
